title: Ghifari's Blog
email: dr.ghifari@gmail.com
description: >-
  Solving imaginary scaling issues
baseurl: ""
url: "https://ghifari.dev"
twitter_username: gdwikir
github_username:  ghifariram

# Build settings
locale: en-US
remote_theme: "mmistakes/so-simple-theme@3.2.0"
logo: "images/gdr-logo.jpg"
date_format: "%-d %B %Y"
read_time: true
words_per_minute: 200
skin: "/assets/css/skins/default.css"
mathjax:
  enable: true
  combo: "tex-svg"
  tags: "ams"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: UA-165991058-1 # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: ghifari-dev # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: gdwikir # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Ghifari Dwiki Ramadhan
  picture: /images/ghifari.jpg
  email: dr.ghifari@gmail.com
  twitter: gdwikir
  links:
    - title: Twitter
      url: https://twitter.com/gdwikir
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/gdwikir
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/ghifariram
      icon: fab fa-github-square
    - title: LinkedIn
      url: https://linkedin.com/in/gdwikir
      icon: fab fa-linkedin

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/gdwikir
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/gdwikir
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/ghifariram
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://linkedin.com/in/gdwikir
    icon: fab fa-linkedin
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

